author: "Nimrod Dayan"
category: "http"
summary: "HTTP POST user's messages to target URL when user is offline"
home: "https://github.com/Nimrodda/mod_http_offline"
url: "https://github.com/Nimrodda/mod_http_offline"
