author: "Ibrahim Koujar <ibrahimkoujar@github>"
category: "log"
summary: "Send offline messages."
home: "https://github.com/processone/ejabberd-contrib/tree/master/"
url: "git@github.com:processone/ejabberd-contrib.git"
